#!/bin/sh
if [ \! -f .hg/nb69src.zip ]
then
  wget -O .hg/nb69src.zip --progress=dot:mega 'http://dlc.sun.com.edgesuite.net/netbeans/6.9/final/zip/netbeans-6.9-201006101454-src.zip'
fi
if [ \! -f .hg/nb69.zip ]
then
  wget -O .hg/nb69.zip --progress=dot:mega 'http://dlc.sun.com.edgesuite.net/netbeans/6.9/final/zip/netbeans-6.9-201006101454-ml.zip'
fi
unzip .hg/nb69.zip
mkdir nb_all
(cd nb_all; unzip ../.hg/nb69src.zip)
ln -sv .. nb_all/contrib
ant -f nb_all/nbbuild/build.xml bootstrap
for m in `cat nb_all/contrib/other/hudson-build-list`; do ant -f nb_all/contrib/"$m"/build.xml -Dnetbeans.dest.dir=$WORKSPACE/netbeans -Dbuildnumber=$BUILD_TAG nbm; done
ant -f nb_all/contrib/other/hudson-build-update-descriptor.xml
