
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 23 23:52:48 CEST 2010
//----------------------------------------------------

package org.netbeans.modules.ada.editor.parser;

/** CUP generated interface containing symbol constants. */
public interface AdaASTSymbols {
  /* terminals */
  public static final int AT = 11;
  public static final int IDENTIFIER = 102;
  public static final int GT = 87;
  public static final int LIMITED = 35;
  public static final int ARROW = 91;
  public static final int AMP = 75;
  public static final int TYPE = 68;
  public static final int SUBTYPE = 63;
  public static final int ALIASED = 7;
  public static final int RAISE = 53;
  public static final int RENAMES = 57;
  public static final int UNTIL = 69;
  public static final int OVERRIDING = 45;
  public static final int ASSIGNMENT = 94;
  public static final int ELSIF = 22;
  public static final int COMMA = 81;
  public static final int TERMINATE = 66;
  public static final int RPAREN = 78;
  public static final int LT = 89;
  public static final int ALL = 8;
  public static final int DECLARE = 16;
  public static final int ABORT = 2;
  public static final int GTGT = 99;
  public static final int LPAREN = 77;
  public static final int ACCESS = 5;
  public static final int LOOP = 36;
  public static final int PROTECTED = 50;
  public static final int OUT = 44;
  public static final int NOT = 39;
  public static final int TASK = 65;
  public static final int ARRAY = 10;
  public static final int THEN = 67;
  public static final int GOTO = 30;
  public static final int PACKAGE = 46;
  public static final int RECORD = 55;
  public static final int EQ = 88;
  public static final int REVERSE = 52;
  public static final int MOD = 37;
  public static final int WHEN = 71;
  public static final int GENERIC = 29;
  public static final int DIGITS = 19;
  public static final int DOT_DOT = 92;
  public static final int SELECT = 59;
  public static final int OTHERS = 43;
  public static final int ABSTRACT = 4;
  public static final int SLASH = 84;
  public static final int PLUS = 80;
  public static final int WHILE = 72;
  public static final int USE = 70;
  public static final int INTERFACE = 33;
  public static final int DO = 20;
  public static final int FOR = 27;
  public static final int EXPON = 93;
  public static final int STAR = 79;
  public static final int RETURN = 51;
  public static final int LTLT = 98;
  public static final int DELAY = 17;
  public static final int ELSE = 21;
  public static final int BASED_LITERAL = 104;
  public static final int GTEQ = 96;
  public static final int DOT = 83;
  public static final int PROCEDURE = 49;
  public static final int ENTRY = 24;
  public static final int DELTA = 18;
  public static final int PRAGMA = 47;
  public static final int STRING_LITERAL = 105;
  public static final int TICK = 76;
  public static final int NULL = 40;
  public static final int BOX = 100;
  public static final int SEMICOLON = 86;
  public static final int EOF = 0;
  public static final int FUNCTION = 28;
  public static final int MINUS = 82;
  public static final int IS = 34;
  public static final int CONSTANT = 14;
  public static final int LTEQ = 97;
  public static final int BODY = 13;
  public static final int ACCEPT = 6;
  public static final int IN = 32;
  public static final int OR = 42;
  public static final int error = 1;
  public static final int EXIT = 26;
  public static final int DECIMAL_LITERAL = 103;
  public static final int SYNCHRONIZED = 62;
  public static final int IF = 31;
  public static final int OF = 41;
  public static final int ABS = 3;
  public static final int END = 23;
  public static final int COLON = 85;
  public static final int REM = 56;
  public static final int REQUEUE = 58;
  public static final int SEPARATE = 60;
  public static final int SOME = 61;
  public static final int INEQ = 95;
  public static final int CHAR_LITERAL = 101;
  public static final int BEGIN = 12;
  public static final int CASE = 15;
  public static final int EXCEPTION = 25;
  public static final int NEW = 38;
  public static final int TAGGED = 64;
  public static final int RANGE = 54;
  public static final int AND = 9;
  public static final int BAR = 90;
  public static final int PRIVATE = 48;
  public static final int WITH = 73;
  public static final int XOR = 74;
}

